### ISSUE TITLE
How to add '-' before and after episode number when renaming files?

### ISSUE THREAD

**Issue by BKR-TN** [ravarage/Tv-Naming#2]
Hello,

Could you tell me how to make file renaming like this:
From:  Series name 01 Episode name
To:  Series name **-**  01 **-**  Episode name

Thanks.

**Comment by ravarage** [comment]
that is not option but its python code it can be easly added 
in the file TVNaming.py in from funtion in  counter in line 432 
I have 3 options that avaialbe in the app you can add - in there to all options or even option to add it from gui or not

**Comment by BKR-TN** [comment]
@ravarage 
I edited lines 448, 460 and 472 and now the program is working like I needed. Thanks a lot.

**Comment by ravarage** [comment]
you are welcome
